// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwy1xQ8nEFfaqJwGUPulpqmvvOZxN2BmI',
    appId: '1:959598773891:web:690c295223af967ae73db6',
    messagingSenderId: '959598773891',
    projectId: 'afrrikia-mdm',
    authDomain: 'afrrikia-mdm.firebaseapp.com',
    storageBucket: 'afrrikia-mdm.firebasestorage.app',
    measurementId: 'G-FGNK3EXX70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAujln86ew_xPE8qpxci6CdQ-HyLobc4AU',
    appId: '1:959598773891:android:6f5c846bf0d41ccfe73db6',
    messagingSenderId: '959598773891',
    projectId: 'afrrikia-mdm',
    storageBucket: 'afrrikia-mdm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQBRYi7tdqUbhmj8MfVhLXFhgOe3FtYk',
    appId: '1:959598773891:ios:ba2bcc9ce77c3befe73db6',
    messagingSenderId: '959598773891',
    projectId: 'afrrikia-mdm',
    storageBucket: 'afrrikia-mdm.firebasestorage.app',
    iosBundleId: 'com.example.domAffrikiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQBRYi7tdqUbhmj8MfVhLXFhgOe3FtYk',
    appId: '1:959598773891:ios:ba2bcc9ce77c3befe73db6',
    messagingSenderId: '959598773891',
    projectId: 'afrrikia-mdm',
    storageBucket: 'afrrikia-mdm.firebasestorage.app',
    iosBundleId: 'com.example.domAffrikiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwy1xQ8nEFfaqJwGUPulpqmvvOZxN2BmI',
    appId: '1:959598773891:web:5c805de8e6e44e72e73db6',
    messagingSenderId: '959598773891',
    projectId: 'afrrikia-mdm',
    authDomain: 'afrrikia-mdm.firebaseapp.com',
    storageBucket: 'afrrikia-mdm.firebasestorage.app',
    measurementId: 'G-8T31ZJT46G',
  );

}