
### Ask for Activation code
POST https://afrrikia.com/api/common/uploadKycInfo
Content-Type: application/json

{
  "name": "Monaba",
  "surname": "Mpiko",
  "birthday": "22/08/2006",
  "phone": "224662564678",
  "idNumber": "string",
  "address": "string",
  "status": "pending",
  "role": "customer",
  "otp": "string"
}

#### Activate Device with bill generation (Using Activation Code)
POST https://afrrikia.com/api/device/activate?code=A00QEW&deviceType=1
Content-Type: application/json
deviceId: 2536278193U2
deviceTypeId: 1

{

}

###
PUT https://afrrikia.com/api/device/updateDeviceStatus?status=2
Content-Type: application/json
deviceId: 9ABEDAE483E0FCAF

{}

# Activate Device (Using Activation Code)
POST https://afrrikia.com/api/device/activation?activeCode=A00QE2
Content-Type: application/json
deviceId: 2536278193U2

{

}


### Get upgrade info
GET https://afrrikia.com/api/common/getUpgradeInfo?version=1
Content-Type: application/json

### Get Bill
GET https://afrrikia.com/api/bill/getBillsByCustomer?customerPhone=243892007346
Content-Type: application/json

### Get bill types
GET https://afrrikia.com/api/bill/getBillTypes
Content-Type: application/json

### Create Bills
PUT https://afrrikia.com/api/bill/createBills?typeCode=month
Content-Type: application/json
deviceId: 2536278193U2

{}

### PayBill
GET https://afrrikia.com/api/bill/payBill?billNo=1922316482419142656
Content-Type: application/json
deviceId: 9ABEDAE483E0FCAF

### Get bills
GET http://afrrikia.com/api/bill/getBillTypes
Content-Type: application/json

### payment
POST https://afrrikia.com/api/pay/gtOrder
Content-Type: application/json
deviceId: 9ABEDAE483E0FCAF

{
  "billNo": "1922809112102440960",
  "payAmount": 2,
  "mobile": "224664757566",
  "description": "bill payment"
}

### get bill payment status

GET http://afrrikia.com/api/pay/getPaymentStatus?orderId=1922811947305144320
Content-Type: application/json
deviceId: 9ABEDAE483E0FCAF


### Create Device type
POST https://afrrikia.com/api/devicetype/create
Content-Type: application/json

{
    "typeName": "Phone",
    "typeModel": "Android",
    "typePrice": 2300.7,
    "typeActivationFee": 200,
}

### Get device typ list
GET http://afrrikia.com/api/api/devicetype/list
Content-Type: application/json




